theislab/cellrank

README.rst
cellrank/plotting/_cluster_fates.py
docs/source/index.rst
setup.py
tests/lineage_test.py

Fix cluster fates

---

cellrank/tools/_markov_chain.py

Fix writing lineage class

---

cellrank/plotting/_cluster_fates.py

Temporarily fixes #21 until https://github.com/theislab/anndata/pull/335 is merged.

Temporary fix for cluster_fates

---

cellrank/tools/__init__.py
cellrank/tools/_root_final.py
cellrank/utils/_docs.py
docs/source/api.rst
setup.py

Find root final

---

cellrank/plotting/_cluster_fates.py
cellrank/plotting/_cluster_lineages.py
cellrank/plotting/_constants.py
cellrank/plotting/_gene_trend.py
cellrank/plotting/_heatmap.py
cellrank/plotting/_utils.py
cellrank/tools/_gene_importance.py
cellrank/tools/_markov_chain.py
cellrank/tools/_root_final.py
cellrank/tools/_transition_matrix.py
cellrank/tools/_utils.py
cellrank/tools/kernels/_kernel.py
cellrank/utils/_utils.py

Minor docs corrections

---

cellrank/plotting/_cluster_lineages.py
cellrank/plotting/_gene_trend.py
cellrank/plotting/_graph.py
cellrank/plotting/_heatmap.py
cellrank/tools/_utils.py
cellrank/tools/kernels/_kernel.py
cellrank/utils/_utils.py
cellrank/utils/models/_models.py

Graph matrix support

---

cellrank/plotting/_cluster_lineages.py
cellrank/plotting/_constants.py
cellrank/plotting/_gene_trend.py
cellrank/plotting/_heatmap.py
cellrank/plotting/_utils.py
cellrank/tools/_gene_importance.py
cellrank/utils/_parallelize.py

Add option to disable progress bar

---

cellrank/plotting/_cluster_fates.py
cellrank/tools/_markov_chain.py

Implement scvelo scatter + paga pie

---

cellrank/plotting/_cluster_fates.py

Add support for multiple legends

---

cellrank/plotting/_gene_trend.py
cellrank/plotting/_heatmap.py

Fix xlabel

---

cellrank/tools/kernels/_kernel.py
tests/_helpers.py

This changes the default value of the sigma parameter in the softmax

Change the default value for sigma

---

cellrank/tools/kernels/_kernel.py
tests/_helpers.py
tests/kernels_test.py

Resparsify transition matrix

---

cellrank/__init__.py
pyproject.toml
setup.py

Package improvements

---

cellrank/__init__.py

Add author and email

---

cellrank/tools/_markov_chain.py

This adds a coloring for real and complex eigenvalues and adds a possibliity to plot eigenvalues in complex plane. Further, for eigenvectors in the embedding, one can choose whether real or imaginary parts are to be visualised.

Complex plot

---

cellrank/plotting/_cluster_fates.py

Add better titles for cluster fates

---

cellrank/tools/_markov_chain.py
cellrank/tools/_utils.py
tests/test_utils.py

Approx rcs improvements

---

cellrank/plotting/_cluster_fates.py
cellrank/tools/_markov_chain.py

This just adds one commit from `mode_gpcca`

Gpcca cherry pick

---

cellrank/__init__.py
cellrank/tools/_markov_chain.py
cellrank/tools/_read.py
tests/test_plotting.py
tests/test_read.py

Load adata

---

cellrank/tools/_lineage.py
cellrank/tools/_utils.py
tests/test_lineage.py

Implements #95 
TODO: write some tests for this functionality.

Lineage improvements

---

cellrank/plotting/_cluster_fates.py
cellrank/plotting/_gene_trend.py
cellrank/plotting/_graph.py
cellrank/plotting/_heatmap.py
cellrank/plotting/_utils.py
cellrank/tools/_markov_chain.py
cellrank/utils/models/_models.py

Unify plotting - capitalize titles, lowercase x- and y-labels

---

cellrank/plotting/_cluster_fates.py
setup.py
tests/test_plotting.py

Move to scvelo.pl.paga, fix basis

---

cellrank/tools/_read.py
cellrank/tools/estimators/_cflare.py
cellrank/tools/estimators/_gppca.py
docs/source/api.rst
docs/source/classes.rst
docs/source/references.rst

Update docs, add GPCCA citation

---

README.rst
docs/source/index.rst

Add binder badge, remove license

---

cellrank/tools/estimators/_base_estimator.py
cellrank/tools/estimators/_gppca.py

Add plot_schur_matrix

---

cellrank/tools/estimators/_base_estimator.py
cellrank/tools/kernels/_kernel.py

This introduces a small fix for the generalized DPT as well as a tiny todo for checking the velo graph before using it.

Minor fixes

---

cellrank/tools/kernels/_kernel.py

This makes the check for connectivity optional, which is the most expensive computation upon initialisation.

Make connectivity check optional

---

cellrank/tools/estimators/_base_estimator.py

This just makes that method a bit more usable/convenient to use.

Imporve the `.compute_lineage_drivers` method

---

cellrank/tools/estimators/_gppca.py

Add cacheing of Schur decomp

---

cellrank/tools/estimators/_base_estimator.py

This fixes gdpt to work with `sorted_schur`

Updating gdpt

---

cellrank/tools/estimators/_base_estimator.py
cellrank/tools/estimators/_gppca.py

Add eigenvals from GPCCA

---

cellrank/tools/_lineages.py
cellrank/tools/_root_final.py
cellrank/tools/_utils.py
cellrank/tools/estimators/_cflare.py
cellrank/tools/estimators/_gppca.py

Implements #163 
@Marius1311 I've opted for `estimator` key which is our class, but can change it to strings (have no strong opinions about this).
I wasn't sure how to best set the lineages for GPCCA, so I just use `set_main_states()` without everything.

High level fn gpcca

---

README.rst
cellrank/plotting/_cluster_fates.py
cellrank/tools/__init__.py
cellrank/tools/_exact_mc_test.py
cellrank/tools/_lineages.py
cellrank/tools/_root_final.py
docs/source/index.rst
tests/test_pipeline.py
tests/test_tools.py
tox.ini

Sorry, that commit message below is confusing. I'm really switiching the default estimator to be GPCCA.

Switch the default estimator to be GPCCA

---

cellrank/plotting/_cluster_fates.py
cellrank/tools/_exact_mc_test.py
cellrank/tools/_lineage.py
cellrank/tools/_utils.py
cellrank/tools/estimators/_base_estimator.py
cellrank/tools/estimators/_gppca.py
tests/test_lineage.py

Gpcca overlap

---

cellrank/tools/_utils.py
cellrank/tools/kernels/_kernel.py

Include a check for symmetry in the sparsity pattern of the velocity graph.

Symmetry Checks

---

cellrank/tools/_lineages.py
cellrank/tools/_root_final.py
tests/test_pipeline.py

Fix when n_states is None

---

cellrank/tools/kernels/_kernel.py

Add check upon reading the velocity graph for the median effective number of neighbors in the velocity graph.

Compute eff k

---

cellrank/tools/estimators/_gppca.py

Fixes #181 
@Marius1311 could you please test this out where it fixes the problem? If yes, I will begin writing tests.

Possible indexing fix

---

cellrank/tools/_root_final.py

Enable using velocity uncertainty through the high level interface.

Enable velo uncert for high level

---

cellrank/plotting/_cluster_fates.py

This does not fix anything, it's a minor rephrasing.

Very minor

---

cellrank/tools/_lineage.py
tests/test_lineage.py

Fix Lineage bug when names/rows are of full shape

---

cellrank/tools/__init__.py
cellrank/tools/_gene_importance.py
tests/test_pipeline.py

So far, this is only possible via the low-level interface. Add possiblitiy to call this from the high level interface.

Add high level function to compute lineage drivers

---

.github/workflows/build_docs_workflow.yml

Add build doc workflow

---

docs/source/installation.rst

A collection of problems encountered at installation at their solution. Related to SLEPSc/PETSc/MPI

Update the installation instr.

---

cellrank/plotting/_graph.py
cellrank/tools/_utils.py
cellrank/tools/estimators/_cflare.py
tests/test_utils.py

There was a bug in Kmeans clustering when the number of samples was smaller than the number of clusters.

Fix one error with kmeans clusterin

---

cellrank/tools/estimators/_cflare.py
tests/test_cflare.py

Uses the solutions of old problems to initialize the new one, only within one recurrent class.

Further speedup for CFLARE

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
README.rst
docs/source/index.rst

New issue templates

---

cellrank/tools/_lineage.py
cellrank/tools/estimators/_base_estimator.py
tests/conftest.py
tests/test_lineage.py

Don't return a copy

---

tests/test_kernels.py

This adds two tests that check whether our transition matrix, computed just based on connectivities, matches with scanpy's non-symmetric transition matrix. There is one test for doing this with and one without density normalization. Both pass on my machine. 
This adds tests. 
closes #219

Add tests for connectivity-based transition matrix

---

cellrank/tools/_utils.py
cellrank/tools/estimators/_base_estimator.py
tests/test_cflare.py

This refactors the computation of absorption probabilities so that it's carried out in chunks by utility functions that we can easily test. We had a logical bug in there which meant that the initialization based on past problems was basically inefficient, so this could also lead to a speedup. 
Need to add some tests.

Refactor computation of absorption probabilities

---

.scripts/ci/before_install.sh
.scripts/ci/install.sh
.scripts/ci/test.sh
.scripts/ci/upload_bioconda.sh
.scripts/ci/upload_coverage.sh
.travis.yml
docs/source/classes.rst
docs/source/installation.rst
setup.py

Installation improvement of SLEPc and PETSc
Add option for `pip install cellrank[krylov]` as a convenience method to install SLEPc and PETSc.
I've added a CI to see if it works.
closes #246

Extra krylov

---

cellrank/tools/_lineage.py
tests/test_lineage.py

Cast non-string keys to strings.
Same as above.
Modified 1 test and added a new one.
closes #267

Convert non-string names to strings

---

.scripts/ci/update_notebooks_readme.sh
.travis.yml
README.rst
docs/source/installation.rst

Add installation instructions for `cellrank-krylov` on Bioconda.
Clean up installation instructions, automate notebooks readme update.
Not applicable.
closes #271

Update installation + automatic notebooks readme updates

---

cellrank/tools/_gene_importance.py
cellrank/tools/_lineages.py
tests/test_tools.py

Clean up high level functions, add tests for `cellrank.tl.lineage_drivers`.
See above.
New tests for `cellrank.tl.lineage_drivers`
closes #285

Fix error msgs, add high level tests for drivers

---

cellrank/plotting/_cluster_lineages.py
cellrank/plotting/_heatmap.py
cellrank/tools/_linear_solver.py
cellrank/tools/_utils.py
cellrank/tools/estimators/_base_estimator.py
cellrank/tools/estimators/_constants.py
cellrank/tools/estimators/_property.py

Add mean absorption time + it's variance.
Add option `absorption_time_moments={None, 'first', 'second'}`.
Also refactored linear solvers (still WIP, maybe create a clas).
It hasn't, but will be later.
closes #294

Time to abs

---

cellrank/tl/estimators/_base_estimator.py
cellrank/tl/estimators/_property.py
cellrank/ul/models/_models.py

Minor QoL changes. @Marius1311 these should fix the issues you've encountered (hopefully).
Better rpy2 error msg, don't compute mean time until absorption by default, fix color scaling for 1 lineage.
No.
closes #306 
closes #307 
closes #309

Minor improvements

---

cellrank/pl/_cluster_lineages.py
cellrank/pl/_gene_trend.py
cellrank/pl/_heatmap.py
cellrank/pl/_utils.py
cellrank/tl/_lineage_drivers.py
cellrank/ul/_docs.py
cellrank/ul/models/_models.py

Add more control over `model.prepare()`.
Add an `callback` argument that can be lineage- and gene-specific for customizing `model.prepare()`.
By default, it just call the prepare method.
No.
closes #324

Add model callback

---

cellrank/tl/estimators/_gppca.py
cellrank/tl/estimators/_property.py

See below.
Fix some bugs in vector plotting (percentile and stationary dist, continuous final states for GPCCA)
No.
closes #338

Fix vector plotting

---

cellrank/tl/_utils.py
cellrank/tl/estimators/_base_estimator.py
cellrank/tl/estimators/_constants.py
cellrank/tl/estimators/_gppca.py
cellrank/tl/estimators/_property.py
tests/test_cflare.py

Disable absorption pseudotime until we know it can be used as one (keep the time to absorption though).

Remove absorption pseudotime

---

cellrank/tl/_colors.py
tests/test_utils.py

Be less restrictive w.r.t. the colors.
Don't require the number of colors to match exactly with the number of categories.
closes #327

Fix too hard color restriction

---

.pre-commit-config.yaml
.scripts/ci/before_install.sh
.scripts/ci/install.sh
.scripts/ci/static_analysis.sh
.scripts/ci/test.sh
.travis.yml
cellrank/tl/_lineage.py
cellrank/tl/_linear_solver.py
cellrank/tl/estimators/_base_estimator.py
cellrank/tl/estimators/_decomposition.py
cellrank/tl/estimators/_gppca.py
cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_precomputed_kernel.py
cellrank/tl/kernels/_utils.py
cellrank/tl/kernels/_velocity_kernel.py
cellrank/ul/_parallelize.py
cellrank/ul/_utils.py
cellrank/ul/models/_base_model.py
setup.py
tests/test_cflare.py
tests/test_pipeline.py
tests/test_plotting.py

Clean up travis a bit

---

cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_utils.py
cellrank/tl/kernels/_velocity_kernel.py
cellrank/ul/_parallelize.py
tests/test_kernels.py

add memory mapping for propagation.
yes.

Memory map

---

cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_connectivity_kernel.py
cellrank/tl/kernels/_velocity_kernel.py
docs/source/references.rst
examples/other/compute_kernel_tricks.py
examples/other/compute_lineage_tricks.py
examples/other/plot_model.py

Update others gallery

---

cellrank/tl/estimators/_base_estimator.py
cellrank/tl/estimators/_property.py
cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_precomputed_kernel.py
cellrank/tl/kernels/_utils.py
cellrank/tl/kernels/_velocity_kernel.py
requirements.txt
tests/_helpers.py
tests/test_cflare.py
tests/test_gpcca.py
tests/test_kernels.py

See below.
Fix writing for Python3.6, update Precomputed kernel, fix copying type information and params propagation.
Yes, many new tests.
closes #389

Fix estimator pickling

---

cellrank/datasets/__init__.py
cellrank/datasets/_datasets.py
cellrank/ul/_docs.py
docs/source/api.rst
docs/source/references.rst

See below.
Add `cellrank.datasets.lung`.
No, but in the future, we will also test for dataset downloads. (it's implicit for preprocessed pancreas).
closes #405 
@Marius1311 
Maybe you could update the docstring, i.e. be more verbose (or warn user that it's quite large)?

Add lung dataset

---

cellrank/datasets/_datasets.py

Expose path and kwargs in dataset

---

cellrank/tl/estimators/_gppca.py
tests/test_gpcca.py

@Marius1311 we already did have something like this, it was `method='min_self_prob'`, but I've renamed it to `method='threshold'.`
closes #413

Rename min_self_prob to threshold

---

cellrank/tl/estimators/_base_estimator.py
cellrank/tl/estimators/_gppca.py
tests/test_cflare.py
tests/test_gpcca.py

Add function `rename_terminal_states` (also update `set_terminal_states_from_macrostates`).
Yes.
closes #417

Allow terminal states rename

---

cellrank/pl/_cluster_fates.py
cellrank/tl/_lineage.py
tests/test_lineage.py

Fix bug in Lineage's fancy indexing (boolean mask + names). Fix cluster_fates colorbar ranges.
Yes, this test fails if the fix is not implemented: https://github.com/theislab/cellrank/pull/426/files#diff-7b22df485f663ef4b937739194fd9728R569
closes #427

Fix Lineage fancy indexing bug, fix colorbars

---

cellrank/tl/estimators/_base_estimator.py
cellrank/tl/estimators/_gppca.py
tests/test_cflare.py
tests/test_gpcca.py

This fixes an isssue in GPCCA when combining and renaming the states in one step.
Yes.
closes #428

Fix rename states in set terminal

---

cellrank/datasets/__init__.py
cellrank/datasets/_datasets.py
tests/test_datasets.py

Add `cellrank.datasets._lung`.
Yes, I've added download tests for pancreas and pancreas preprocessed.

Test datasets

---

cellrank/datasets/_datasets.py

Update dataset
Update dataset on figshare

Updated the pancreas object with pseudotime

---

.scripts/ci/before_install.sh
.scripts/ci/install.sh
.scripts/ci/static_analysis.sh
.travis.yml
cellrank/pl/_init_term_states.py
cellrank/pl/_lineages.py
cellrank/tl/estimators/_base_estimator.py
cellrank/tl/estimators/_property.py
cellrank/ul/_docs.py
cellrank/ul/models/_base_model.py
cellrank/ul/models/_gamr_model.py
cellrank/ul/models/_pygam_model.py
docs/source/references.rst
docs/source/release_notes.rst
tests/test_model.py

Add linkcheck from sphinx-builder, add `basis` to plotting docstrings.
closes #384 (until Python-3.9 non-dev is avaiable on Travis - currently it takes too long to install the deps.) 
closes #397
closes #439

Add link testing to static analysis

---

README.rst
docs/source/index.rst

Add info to the README files
This adds the link to our preprint and a short explanation of the name `CellRank`
No testing necessary, only docs.

Add the preprint link

---

cellrank/datasets/__init__.py
cellrank/datasets/_datasets.py
docs/source/api.rst
tests/test_datasets.py
vendorize.toml

Expose `cellrank.datasets.lung`, fix `msmtools` pointing to wrong version in `vendorize.toml` (sometimes, a large dense
matrix was created that causes memory issues).
#441

Expose lung, fix msmtools version

---

cellrank/datasets/_datasets.py
docs/source/latest_additions.rst

Add `cellrank.datasets.reprogramming`.
Add reprogramming dataset from add_new_terminal_states_method 
Not and it will not be (on CI), since the data  has ~1.5 GiB.
closes #448

Add more TODOs

---

cellrank/pl/_utils.py

Tiny change to utility function that introdes a `fontsize` argument
as above
Not at all. I think it's fine since this utility function isn't even exposed to the user and isn't used anywhere internally.

Add fontsize argument to pie chart

---

.github/workflows/ci.yml
.pre-commit-config.yaml
.readthedocs.yml
cellrank/tl/estimators/_property.py
cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_velocity_schemes.py
cellrank/ul/models/_base_model.py
tests/test_lineage.py

Fixes unnecessary installation during linting. Also add new pre-commits.
Removed `pip install -e.[dev,test]` with `pip install pre-commit`
By running the CI.
closes #467

Fix installation during linting, add pre-commits

---

cellrank/logging/_logging.py
requirements.txt

Remove vendorize req., add pyGPCCA to version log

---

.pre-commit-config.yaml
cellrank/tl/_init_term_states.py
cellrank/tl/_transition_matrix.py
cellrank/tl/estimators/_cflare.py
cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_connectivity_kernel.py
cellrank/ul/_utils.py
docs/source/conf.py
docs/source/references.rst
tests/test_kernels.py
tests/test_tools.py

Expose `conn_key` in `ConnectivityKernel`'s constructor
3 new tests (1 for low-level, 2 for high-level).
closes #493 
TODOs:
_transition_matrix.py,
kernels/_connectivity_kernel.py}`
@Marius1311 could you please handle the docstrings? Would need to just rephrase a bit (mention spatial data, etc.).

Expose conn_key in ConnectivityKernel

---

cellrank/tl/kernels/_base_kernel.py
tests/test_kernels.py

Fix emb proj

---

cellrank/datasets/__init__.py
cellrank/datasets/_datasets.py
docs/source/api.rst
docs/source/references.rst

New dataset for tutorials.
No tests.

Zebrafish dataset

---

cellrank/tl/estimators/_base_estimator.py
tests/test_cflare.py

Raise `ValueError` of absorption probabilities do not sum to 1 in `BaseEstimator`.
2 new tests added.
closes #560

Add check probs sum to 1

---

cellrank/tl/kernels/_pseudotime_kernel.py
cellrank/tl/kernels/_pseudotime_schemes.py

Fixes not passing percentile into the soft threshold scheme.

Fix not using percentile

---

requirements.txt

Remove unnecessary requirements.
`wrapt` will be handled after #564 .
`networkx` will be dealt with in a separate issue, just need to reimplement https://networkx.org/documentation/networkx-1.10/_modules/networkx/algorithms/components/connected.html#is_connected (amounts to just 1 BFS search).
`numba>=0.53.0` has still some problems with `umap-learn`.
By running the CI.
closes #569

First version of req. pruning

---

cellrank/tl/estimators/_base_estimator.py
cellrank/tl/estimators/_gpcca.py
tests/test_gpcca.py
tests/test_pipeline.py

Add more checks when reading data from adata, remove `macrostates` from adata.obsm/self when calling
`set_terminal_states` and the names differ.
Not yet.
closes #562

Fix inconsistent state

---

README.rst
docs/source/index.rst

update preprint URL from v1 to v2

---

cellrank/tl/_init_term_states.py
cellrank/tl/_transition_matrix.py
tests/test_tools.py

Add `force_recompute: bool = False` to `cellrank.tl.{initial,terminal}_states`.
1 new parametrized test.
closes #575

Add force recompute tmat

---

cellrank/tl/kernels/_pseudotime_schemes.py
tests/test_kernels.py

Remove `-1` when determining `k_thresh` in `PseudotimeKernel`.
Modify test for existing `frac_to_keep` values (15 in total)
closes #559

Hard threshold scheme adjustment

---

cellrank/external/kernels/_statot_kernel.py
cellrank/pl/_gene_trend.py
cellrank/tl/estimators/_base_estimator.py
cellrank/tl/estimators/_cflare.py
cellrank/tl/estimators/_decomposition.py
cellrank/tl/estimators/_gpcca.py
cellrank/tl/estimators/_property.py
cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_connectivity_kernel.py
cellrank/tl/kernels/_precomputed_kernel.py
cellrank/tl/kernels/_pseudotime_kernel.py
cellrank/tl/kernels/_velocity_kernel.py
cellrank/ul/_docs.py
cellrank/ul/models/_base_model.py
cellrank/ul/models/_gamr_model.py
cellrank/ul/models/_sklearn_model.py
docs/requirements.txt
docs/source/conf.py
examples/estimators/compute_terminal_states_gpcca.py
examples/other/compute_kernel_tricks.py
examples/other/compute_lineage_tricks.py

Remove `sphinx-paramlinks` (long overdue) since it's broken with sphinx 4.0 (which came just a few hours ago)

Remove paramlinks

---

cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_cytotrace_kernel.py
cellrank/tl/kernels/_precomputed_kernel.py
cellrank/tl/kernels/_pseudotime_kernel.py
cellrank/tl/kernels/_pseudotime_schemes.py
cellrank/tl/kernels/_velocity_kernel.py
cellrank/ul/_docs.py
docs/source/conf.py
tests/test_kernels.py

Change PT kernel defaults, remove percentile/dnorm from arguments.
New defaults: `nu: 1.0 -> 0.5; b: 20 -> 10`.

Pt kernel changes

---

cellrank/tl/kernels/_pseudotime_kernel.py
cellrank/tl/kernels/_pseudotime_schemes.py
tests/test_kernels.py

Self explanatory.
New test has been added.

Parallelize pt kernel

---

cellrank/external/kernels/_statot_kernel.py
cellrank/external/kernels/_wot_kernel.py
cellrank/tl/kernels/_base_kernel.py
tests/test_external.py

Remove connectivities req. for external kernels (add an option to disable it for others as well).
2 new tests.
closes #599

Wot kernel graph

---

cellrank/external/kernels/_wot_kernel.py
cellrank/tl/kernels/_exp_time_kernel.py
tests/test_external.py

Add option to WOT kernel to use transition derived from ConnectivityKernel for the last time point.
Modified existing test.
closes #608

Add option to use connectivities for WOT

---

cellrank/ul/_parallelize.py

See the issue.
No.
closes #614

Fix tqdm/ipywidgets

---

cellrank/tl/kernels/_exp_time_kernel.py
tests/test_external.py

Fix exp time kernel copy

---

cellrank/tl/_utils.py
cellrank/tl/estimators/_base_estimator.py
tests/test_tools.py

See title.
Parametrized existing test.
closes #622

Fix lineage drivers to allow for combinations

---

.github/workflows/ci.yml
cellrank/ul/_parallelize.py
tests/test_utils.py

Fix more jobs than work for sparse matrices in `parallelize`.
1 new test
closes #632

Fix parallelize too many jobs

---

cellrank/tl/estimators/_base_estimator.py
tests/test_cflare.py

Changes the computation of absorption probabilities according to @Marius1311 suggestion in #619.
Unit tests already exist. `tests/test_cflare.py::TestCFLARE.test_abs_probs_negative` needs to be updated.
Closes #619.

Speed up calculation of absorption probabilities

---

docs/source/references.bib

Add a few references
See title.

Add some references

---

.gitignore

Udpates `.gitignore` to not track vscode related directories.
Closes #672.

Ignore vscode related directory

---

.github/workflows/news.yml
docs/source/create_news_fragment.py

Fix minor typos in news generation.

Fix news.yml and run pre-commit

---

.github/workflows/news.yml

Fix news generation v3

---

.github/workflows/news.yml

Fix news/release notes generation CI.

Do not use head ref when checking out

---

.github/workflows/news.yml

Fix towncrier release generation CI.

Add towncrier token

---

.github/workflows/ci.yml
.github/workflows/news.yml

Update towncrier to display development release notes.

Fix news generation yml

---

.github/workflows/news.yml

Allow towncrier to generate bleeding-edge development notes.

Fix not installing requirements + not checking RST

---

.github/workflows/news.yml
docs/source/release/changelog/710.bugfix.rst

Allow towncrier to generate bleeding-edge development notes.

Add better commit msg format, install cellrank

---

.github/workflows/news.yml
docs/source/release/changelog/711.bugfix.rst

Allow towncrier to generate bleeding-edge development notes.

Reset and checkout before committing

---

cellrank/ul/models/_base_model.py
tests/test_model.py

Fix models not properly resetting all its fields when running :meth:`cellrank.ul.models.BaseModel.prepare`.

Fix model reset

---

.github/workflows/test.yml
tests/test_kernels.py
tox.ini

Add Python 3.9 CI testing.
N/A
N/A
N/A

Enable 3.9 CI

---

.github/workflows/deployment.yml
.github/workflows/news.yml
.github/workflows/release.yml
.github/workflows/test.yml
README.rst
cellrank/datasets/_datasets.py
cellrank/tl/estimators/_base_estimator.py
docs/Makefile
docs/source/api.rst
docs/source/conf.py
docs/source/index.rst
docs/source/release/notes-1.3.0.rst
tox.ini

Fix CI workflow deployment files. Add QoL ``tox`` changes.
N/A
N/A
closes #739

Fix workflow files

---

.github/workflows/test.yml
cellrank/tl/_utils.py
cellrank/tl/estimators/terminal_states/_gpcca.py
cellrank/tl/estimators/terminal_states/_term_states_estimator.py
setup.py
tests/test_external.py
tox.ini

Fix when associating term/macro states assignment when reference is not categorical string.
TODO.
closes #749

Fix term/macro states dtype mixture

---

README.rst
docs/requirements.txt
docs/source/_ext/edit_on_github.py
docs/source/_templates/autosummary/base.rst
docs/source/_templates/autosummary/class.rst
docs/source/_templates/autosummary/function.rst
docs/source/_templates/breadcrumbs.html
docs/source/conf.py
docs/source/modurl.py

Reintroduce **Edit on GitHub** button.
closes #752

Add Edit on GitHub

---

cellrank/ul/models/_base_model.py
cellrank/ul/models/_pygam_model.py

Ignore :mod:`pygam` deprecation warnings.
No tests.
closes #794

Fix pyGAM deprecation warnings

---

cellrank/pl/_cluster_fates.py

Update PAGA message in cluster_fates

---

.pre-commit-config.yaml
.readthedocs.yml
docs/source/conf.py

Fix plot_gallery

---

cellrank/estimators/mixins/_utils.py

Prefer plotting macrostates/terminal in a discrete way.
N/A
closes #907

Prefer plotting of discrete values

---

cellrank/kernels/_base_kernel.py
cellrank/kernels/_precomputed_kernel.py
cellrank/kernels/mixins/_kernel.py
tests/test_kernels.py

Add :meth:`cellrank.kernels.Kernel.from_adata`.
TODO.
closes #905

Allow reading kernels from AnnData

---

cellrank/_utils/_utils.py
cellrank/estimators/mixins/_absorption_probabilities.py
cellrank/estimators/terminal_states/_gpcca.py
tests/test_cflare.py
tests/test_utils.py

Use ``", "`` instead of ``" or "`` when joining states.
Updated previous tests.
N/A

Replace ` or ` with `, ` when joining state names

---

cellrank/_utils/_utils.py
tests/_helpers.py

Fix sparse array conversion in ``networkx>=3.0``.
N/A
closes #977

Fix `networkx>=3.0`

---

docs/requirements.txt
docs/source/_static/css/override.css
docs/source/about/team.rst
docs/source/conf.py

Polish team page.
N/A.
closes #956

Polish team page

---

docs/source/release/changelog/994.bugfix.rst

* Removes release note for #994.
Closes #995.

Remove `994.bugfix.rst`

---

cellrank/models/_gamr_model.py

Use :mod:`rpy2`'s local converter.
N/A
closes #1001

Use `rpy2`'s `localconverter`

---

cellrank/kernels/_cytotrace_kernel.py
cellrank/kernels/_pseudotime_kernel.py
cellrank/models/_gamr_model.py
tests/test_kernels.py

Invert the pseudotime when passing ``backward = True`` in :class:`~cellrank.kernels.PseudotimeKernel` and :class:`~cellrank.kernels.CytoTRACEKernel`.
1 new tests
closes #1009

Update Pseudotime/CytoTrace kernel

---

cellrank/estimators/mixins/_lineage_drivers.py

Fix `adjustText` modifying data in-place.
No new tests.
closes #1033

Fix `adjustText` modifying data in-place

---

docs/source/references.bib

[ci skip] Add references for Hhex

---

cellrank/estimators/terminal_states/_gpcca.py

Fix not passing ``kwargs`` in ``set_{initial,terminal}_states``.
No new tests.
closes #1028

Pass `kwargs` in `set_{initial,terminal}_states`

---

cellrank/kernels/_transport_map_kernel.py
tests/test_kernels.py

Rename ``sparsify`` -> ``sparse_mode``.
Updated the test.
N/A

Add `sparse_mode` instead of `sparsify`

---

.gitignore

Add .DS_Store files in the .gitignore

[skip ci] Add Mac OS specifics to .gitignore

---

README.rst
docs/about/index.rst
docs/about/version2.rst
docs/index.rst

Update the READMEs, add a note about moving to version 2, fix smaller issues throughout the docs.

Update the documentation

---

docs/api/datasets.rst
src/cellrank/datasets.py

Remove `pancreas_preprocessed` dataset
closes #1065 
closes #1066

Remove `pancreas_preprocessed`

---

.github/workflows/test.yml
docs/about/version2.rst
docs/api/kernels.rst
src/cellrank/kernels/__init__.py
src/cellrank/kernels/_real_time_kernel.py
tests/test_kernels.py

Rename `TransportMapKernel` -> `RealTimeKernel`
No new tests.
closes #1075

Rename `TransportMapKernel` -> `RealTimeKernel`

---

docs/about/index.rst

Just edits the docs; includes a bit of extra information on how we use sparsity to scale our computations.

Include more on sparsity and scalability

---

src/cellrank/pl/_heatmap.py

* Add argument `gene_order` to `heatmap` function to plot genes in a user-defined order.
Closes #1095.

Allow custom gene order in heatmap

---

docs/about/cite.rst
docs/about/index.rst
docs/index.rst
docs/references.bib

Add a journal to the CellRank 2 preprint link, change the way we link to different kernels in the citation guide, some minor changes in wording. Only docs.

Fix journal entry, small modifications

---

src/cellrank/pl/_circular_projection.py

Replaced "deprecated_arg_names" with "renamed_arg", it has the same functionality

Fix/importError #1183

---

src/cellrank/estimators/mixins/decomposition/_schur.py
src/cellrank/kernels/_cytotrace_kernel.py
src/cellrank/kernels/utils/_projection.py
src/cellrank/kernels/utils/_random_walk.py
src/cellrank/kernels/utils/_tmat_flow.py
src/cellrank/models/_utils.py
tests/_helpers.py
tests/test_kernels.py
tests/test_linear_solver.py
tests/test_plotting.py

Use `toarray()` instead of `.A`

---

src/cellrank/__init__.py
src/cellrank/_utils/_lineage.py
src/cellrank/models/_pygam_model.py
tests/test_lineage.py

* Replace `np.array( , copy=False)` with `np.asarray()`.
Closes #1253.

Fix CI for Python 3.12
