cellrank/tools/_markov_chain.py
cellrank/tools/_utils.py

This always leaves the eigendecomposition complex, but gives a warning in case complex ev's are considered for end point computation.

Leave ev's complex but issue warning

---

cellrank/tools/_utils.py
tests/test_utils.py

Hi @michalk8 , I had to add one line to get this to work, otherwise I got the following error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-54-480cface07f3> in <module>
1 mask_bcs = list(adata_t[mask].obs_names[:40])
----> 2 mc_fwd.set_approx_rcs({cl: mask_bcs}, cluster_key='clusters', add_to_existing=True)
~/Projects/cellrank/cellrank/tools/_markov_chain.py in set_approx_rcs(self, rc_labels, cluster_key, en_cutoff, p_thresh, add_to_existing)
612                 )
613             rc_labels = _merge_approx_rcs(
--> 614                 self.approx_recurrent_classes, rc_labels, inplace=False
615             )
616 
~/Projects/cellrank/cellrank/tools/_utils.py in …
```

Fix bug with merging cats

---

cellrank/tools/estimators/_base_estimator.py

This is a quick adaptation of DPT to use the schur vectors. So far only supports method krylov schur, so if no SLEPs installed, it won't work. Depending on where we want to take this, we will have to change the workflow a bit so that the Schur decomposition is computed once in the beginning and saved, so that multiple methods downstream can make use of it.

Add quick implementation of schur dpt

---

cellrank/tools/_constants.py
cellrank/tools/estimators/_gppca.py

Fixes #111  #122 , #117 
@Marius1311 I reluctantly did as you've suggested and opted NOT to save to `adata.obs` when plotting `n_cells!=None`. However, I think this might confusing for user, having `X` cells saved and `Y` cells not. The `saving` approach is on the other hand a bit redundant: `plot_main_states` with different that `n_cells` when calling `set_main_states` will be overwritten, making the previous choice useless.
One option would be instead of having `n_cells=...` have `plot_categorical={True,False}`, but this is clunky in a way that user has to call `set_main_states(...)` and then `plot_main_states(...)` to visualize different `#cells`.

Root final improvements

---

cellrank/tools/estimators/_base_estimator.py
cellrank/tools/estimators/_gppca.py

Enable setting the number of Lanczos vectors when running `scipy.sparse.linalg.eigs`

Enable setting ncv

---

cellrank/tools/estimators/_base_estimator.py
cellrank/tools/estimators/_cflare.py
tests/test_markov_chain.py

This 
- make the first eigenvector constant for irr. mat, just for plotting (num. errors cause it not to be const. )
- changes naming to be consistent with GPCCA class

Adapt CFLARE 

---

cellrank/tools/kernels/_kernel.py

this checks whether the velocity graph from scvelo has been computed using `n_recurse_neighbors` either 0 or 1 and `mode_neighbors='connectivities'`, which are important settings.

Check velocity graph parameters

---

cellrank/tools/estimators/_gppca.py

Implements #138 
@Marius1311 I need your feedback on this. I've decoupled the computation of Schur vectors and the metastable states - there's the function `compute_schur(n_vectors, init_dist, method, which)` which just calls (`_do_schur_helper`). Afterwards, you can plot the vectors/matrix using `plot_schur_embedding()` or `plot_schur_matrix()`.
Then, you can specify number of states in `compute_metastable_states` - if it's <= #previously computed vectors, you don't recompute it, otherwise, it warns you and computes the new decomposition.
In #138 2., you also mention the ED - however, as it currently stands, there's no way for me to access it or pass it to `msmtools.GPCCA`. I'd leave it for now.
Let me know what you think and whether this is what you've wanted. If so, I will merge and …

Add compute_schur

---

cellrank/tools/kernels/_kernel.py

This changes the way we complain when we don't find velocity uncertainties in the AnnData object, and when we compute the transtition matrix.

Uncertainty warnings

---

cellrank/tools/_colors.py
cellrank/tools/_lineage.py
cellrank/tools/_utils.py
cellrank/tools/estimators/_gppca.py
tests/test_lineage.py
tests/test_pipeline.py
tests/test_utils.py

This changes the way in which we select cells. The central piece is a new utility function `_fuzzy_to_discrete`. This function is class-independent and should make it easier to write tests. 
The new selection function considers overlaps between all states and offers two different possibilities for dealing with it, see the docstring of `_fuzzy_to_discrete` for more details.

Refactor select cells

---

cellrank/tools/_utils.py
cellrank/tools/estimators/_gppca.py
tests/test_pipeline.py

This removes the **kwargs from the 1-state case method of the gpcca estimator

**kwargs for 1-state case

---

cellrank/tools/estimators/_gppca.py

Before taking the max per row, I scale each individual membership vector to [0, 1]. This way, each root/final state will for sure be mapped to one in the aggregated vector.

Change the way state_probs are computed

---

cellrank/tools/_utils.py
cellrank/tools/estimators/_cflare.py
cellrank/tools/estimators/_gppca.py

There was an issue with creating combined annotations for root & final states when using the CFLARE estimator, this is an easy fix.

Enable root final plotting for both estimators

---

cellrank/tools/_utils.py

This adds a utility function to easily retrieve colors from adata.uns in a defined order.

Add utility function to get colors in defined order

---

cellrank/tools/estimators/_gppca.py

Makes that function a bit easier to call. Long term, should make this a class independent utility function anyways.

Remove the metastable assignment

---

cellrank/tools/estimators/_cflare.py
tests/test_cflare.py

This adds a parmeter 'densify' which is `False` by default. Introduced this becasue memory requirements explode for large matrices. 
to do's
- write test that check equality between both solvers
closes #205

Sprase cflare

---

cellrank/tools/kernels/_kernel.py

If there are no velocity variances, we set `scale_by_variances = False`. This changes the printed property in the kernel object.

Minor change to velo kernel with velo uncert

---

cellrank/plotting/_cluster_fates.py

Exposes an option to set a lineage key for `cluster_fates`

Allow passing a lineage key to ease benchmarking

---

cellrank/plotting/_cluster_fates.py

This changes the default in `cr.pl.cluster_fates` to plot a direted PAGA if PAGA has been computed using scvelo.

By default, use transitions_conf

---

cellrank/tools/kernels/__init__.py
cellrank/tools/kernels/_kernel.py
tests/_helpers.py
tests/test_kernels.py

Implements #214 
It will create an empty adata object if None is specified, because we save stuff there.
You can still include it if needed.

Precomputed kernel

---

cellrank/tools/estimators/_cflare.py
tests/test_cflare.py

This fixes a stupid bottleneck in the computation of abs probs which was related to selecting indices. More importantly, it enables using iterative solvers for the linear problem. So far, I'm using GMRES, but bicgstag also looked promising. The iterative solvers are powerful if the matrices are sparse, very large and I'm not computing too many absorbing cells.

Speedup for CFLARE

---

.bumpversion.cfg
.gitignore
.pre-commit-config.yaml
.readthedocs.yml
.travis.yml
README.rst
cellrank/__init__.py
cellrank/tools/estimators/_gppca.py
docs/source/_static/css/custom.css
docs/source/conf.py
docs/source/index.rst
docs/source/installation.rst
docs/source/release_notes.rst
pyproject.toml
setup.py
tox.ini
vendorize.toml

Fix versioning

---

cellrank/tools/kernels/_kernel.py

There was a problem in the kernel class in case the velocity graph and the uncertainties don't align. Rather than raising a warning, an exception was thrown.

Added minor check

---

cellrank/tools/estimators/_base_estimator.py
cellrank/utils/_parallelize.py

Parallelize solving of the system when computing absorption probabilities.
Added an option to solve the system in parallel, default is still sequential.
No unit tests yet - I will add one test using parallel option.
##Benchmarking
For now, only on pancres, 20 lineages.
Before:
1.12 s ± 23.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
After:
954 ms ± 14.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
closes #256 
@Marius1311 
There was previously this line: `x0 = None if ix in init_indices else x`, but it doesn't seem correct: https://github.com/theislab/cellrank/blob/master/cellrank/tools/estimators/_base_estimator.py#L419. Am I wrong?
```

Add parallel to iterative_solver

---

cellrank/plotting/_gene_trend.py
cellrank/tools/_utils.py
cellrank/tools/estimators/_base_estimator.py
cellrank/tools/estimators/_cflare.py
cellrank/tools/estimators/_gppca.py
cellrank/utils/_parallelize.py
cellrank/utils/_utils.py
tests/conftest.py
tests/test_cflare.py
tests/test_gpcca.py

Add PETSc linear solver to solve the equations for lineage absorption probabilities.
On the server, the scipy method didn't finish in 3 hours for 100k+ cells, 3 states. If we really want to use abs. probs.
instead of GPCCA vectors, we need to speed it up. I haven't benchmarked this on the server (still queuing...), but look promising on pancreas:
337 ms ± 15.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
I've added 1 test function which compares `gmres` from scipy and petsc.
closes #260 
- lung: 0:02:48
- lung with 4 parallel jobs (total of 150 systems, as above): 01:23
- server data: 05:33 (16 cores, 4 parallel jobs)

Add PETSc solver

---

cellrank/tl/_transition_matrix.py
cellrank/tl/kernels/_velocity_kernel.py

Minor: expose the n_jobs parameter
Allow the user to specify the number of cores for transition matrix comptuation in high level mode. 
I haven't added any new tests.

Expose the n_jobs parameter in the transition matrix function

---

cellrank/tl/_linear_solver.py
cellrank/tl/_utils.py
cellrank/tl/estimators/_base_estimator.py
cellrank/tl/estimators/_constants.py
cellrank/tl/estimators/_property.py
tests/test_cflare.py

Add time to absorption only to specified lineages.
I've added key `time_to_absorption='Alpha'` or `time_to_absorption=['Alpha', 'Beta:var']` to calculate mean time til absorption + variance to the specific lineage. Also rename
It hasn't.
#339 
Only singleton absorbing states are supported, but we can combine them, such as `'Alpha, Beta'`.
@Marius1311 would be great if you could give it a go on the lung data.

Lineage absorption time

---

cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_connectivity_kernel.py
cellrank/tl/kernels/_palantir_kernel.py
cellrank/tl/kernels/_precomputed_kernel.py
cellrank/tl/kernels/_velocity_kernel.py
tests/test_kernels.py

Propagation transition matrices to complex kernel expressions.
`switch_trasition_matrix` is now available to all kernels and expression, the matrices can be accessed as `.transition_matrices`.
This was done because I expect in the future, we will introduce some stochasticity in other methods.
Yes, many times.
closes #355

Fix propagation

---

README.rst
cellrank/tl/_transition_matrix.py
cellrank/tl/_utils.py
cellrank/tl/estimators/_gppca.py
cellrank/ul/_docs.py
docs/source/index.rst
tests/test_gpcca.py
tests/test_kernels.py
tests/test_tools.py

See below.
Update docs, change default for `cr.tl.transiton_matrix` add `_compute_initial_states` for GPCCA.
Yes, new tests for the new functions.
#401
#402
#403

Compute initial states

---

cellrank/tl/_colors.py
tests/test_colors.py
tests/test_utils.py

Updated the categorical colormap (use scanpy's vega_20 as first 20 colors).
closes #419

Use scanpy's vega_20 colors first

---

cellrank/tl/_utils.py
requirements.txt

Pandas indexing error `cr.tl.lin_drivers` for `pandas==1.0.1`.
No, for `pandas==1.2.0` that I have locally, it was fine and the proposal in #474 fixes this.
Also bumps pandas min. req to `1.0.0` and max. docrep to `0.3`
closes #474

Fix lineage drivers, bump/restrict some reqs

---

cellrank/pl/_graph.py
cellrank/pl/_utils.py
cellrank/tl/_lineage.py
cellrank/tl/estimators/_decomposition.py
cellrank/ul/models/_base_model.py

Really simple fix when I want to show no legend when plotting
This enables showing no legend in the `_plot_real_spectrum` method when passing `legend="none"`
Not at all.

Enable showing no legend

---

cellrank/tl/kernels/_utils.py

@carynwillis
Could you please try the fix I've introduces in this branch? You should be able to install it as
```bash
pip install git+https://github.com/theislab/cellrank@add_explicit_copy
```
To verify it's the correct version, you can run:
```python
import cellrank as cr
print(cr.__full_version__)  # should be '1.2.0+gb5a843b'
```
Explicitly copy the arrays before converting them to CSR matrices.
No, because I am not sure how to reproduce this.
closes #483

Add explicit copy to fix #483

---

cellrank/tl/_utils.py
cellrank/tl/kernels/_base_kernel.py
tests/test_kernels.py
tests/test_tools.py

Do not force transiton matrix to be sparse if it's not sparse, do not construct dense array in dens. norm,
force tmat to be always f64.
Add test to see if sparse/dense is preserved + f64 is retained.
related #585

Dont force sparse tmat if already dense

---

cellrank/tl/_transition_matrix.py
cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_connectivity_kernel.py
cellrank/tl/kernels/_cytotrace_kernel.py
cellrank/tl/kernels/_precomputed_kernel.py
cellrank/tl/kernels/_pseudotime_kernel.py
cellrank/tl/kernels/_velocity_kernel.py
cellrank/ul/_utils.py
tests/test_kernels.py
tests/test_plotting.py

Fix reading connectivities in kernels (previously, connectivities for dens. norm was not accesible for some kernels).
Note that `cr.tl.kernels.ConnectivityKernel(adata, conn_key='neighbors')` will work iff
`scanpy.pp.neighbors(adata, key_added='neighbors')` was run before, not if `scanpy.pp.neighbors(adata, key_added=None)`
(both write `adata.uns['neighbors']`, but `conn_key` really looks into `adata.obsp`.
Yes, new test to see if all kernels can correctly read the connectivities.
closes #589

Fix custom connectivities key

---

cellrank/external/kernels/__init__.py
cellrank/external/kernels/_statot_kernel.py
cellrank/external/kernels/_wot_kernel.py
cellrank/tl/_utils.py
cellrank/tl/kernels/__init__.py
cellrank/tl/kernels/_base_kernel.py
cellrank/tl/kernels/_exp_time_kernel.py
docs/source/classes.rst
docs/source/external_api.rst
docs/source/references.rst
qgq
setup.py
tests/test_external.py

Add Waddington OT kernel, see related issue https://github.com/broadinstitute/wot/issues/91. I've also added option to use existing obs features (PCA, imputed expression) to compute the cost matrices.
Also adds `ExpTimeKernel` class which can be later used to derive kernels with experimental time.
@Marius1311 I've decided against adding anything to the block diagonal, don't think it's a nice solution - user can always weight with full `ConnectivitiesKernel` and afaik, the GPCCA stability issues were gone (I've used small weights like 0.05 or so for connectivities). Maybe you add some nice note in `.compute_transition_matrix`, below `Returns` as
```
Notes
-----
...
```
I've added a few.
closes #551

Exp time kernel

---

cellrank/tl/_utils.py
cellrank/tl/estimators/_base_estimator.py
tests/test_gpcca.py

Update the docstring for `estimator.set_terminal_states`. 
Was outdated. @michalk8, if possible, could you please add the following two functionalities (additionally to what we currently have):
- allow dict's of the form `{'cluster_key_from_obs': ['cluster_1', 'cluster_2', ...]}, i.e. directly use a subset of pre-defined clusters to define terminal states
- if real-time annotations are present, add a mechanism such that terminal states can be restricted to come from a certain time-point (optionally). 
If the second point is too difficult, don't worry, then we don't do it. 
closes #606

Update docstring to manually set terminal states

---

cellrank/tl/kernels/_pseudotime_kernel.py
cellrank/tl/kernels/_pseudotime_schemes.py

The value for `frac_to_keep` should fall in the interval `[0, 1]`. If
this is not the case, an error is thrown and the function exited.
Checks that `frac_to_keep` lies within `[0, 1]`.
Closes #659.

Check value of frac_to_keep is admissible

---

cellrank/pl/_cluster_fates.py
cellrank/tl/_colors.py
cellrank/tl/_lineage.py
cellrank/tl/_utils.py
cellrank/ul/models/_base_model.py
tests/test_lineage.py

Deprecates NumPy data types in favor of builtin ones, e.g. `np.bool` by `bool`.
N/A
Closes #717.

Deprecate NumPy data types

---

cellrank/tl/kernels/_base_kernel.py
tests/test_external.py

Restricts computation of embedding projection to kNN based kernels.
`TestOTKernel` and `TestWOTKernel` are extended by one unit test each to verify that expected error is thrown.
Closes #668.

Restrict embedding projection to knn based kernels

---

cellrank/external/kernels/_wot_kernel.py
tests/test_external.py

Fix :func:`cellrank.external.kernels.WOTKernel.compute_transition_matrix` silently ignoring unexpected kwargs.
closes #721

Fix WOT unused kwargs

---

.github/workflows/news.yml
cellrank/tl/kernels/_exp_time_kernel.py
tests/test_external.py

Fix color creating in :class:`cellrank.tl.kernels.ExperimentalTimeKernel`.
1 new test.
closes #782

Fix exp. time kernel colors

---

cellrank/tl/kernels/_velocity_kernel.py
tests/test_kernels.py

Do not save enums in :class:`anndata.AnnData`.
1 new test.
closes #840

Do not save Enums in AnnData

---

cellrank/tl/_lineage.py
cellrank/tl/estimators/terminal_states/_gpcca.py
requirements.txt

Fix writing :class:`cellrank.tl.Lineage` when saving :class:`anndata.AnnData`.
Will be tested in the follow-up PR.
partially addresses #777

Fix lineage class serialization

---

cellrank/pl/_gene_trend.py
cellrank/pl/_heatmap.py

Add ``return_figure`` option to :func:`cellrank.pl.heatmap` which will return the underlying figure object to be edited directly.
No testing done.
closes  #869

Add option to export plot in pl.heatmap

---

cellrank/kernels/utils/_random_walk.py

Fix initial/terminal points size in random walk.
No new tests.
closes #927

Fix start/end indices size in random walks

---

cellrank/kernels/_base_kernel.py
cellrank/kernels/_connectivity_kernel.py
cellrank/kernels/_pseudotime_kernel.py
cellrank/kernels/_velocity_kernel.py
cellrank/kernels/mixins/_kernel.py
cellrank/kernels/utils/__init__.py
cellrank/kernels/utils/_projection.py
docs/source/release/notes-dev.rst
tests/test_external.py
tests/test_kernels.py

Allow passing connectivities for transition matrix projection. Useful when the kernel is not kNN-based.
1 new test, modified existing tests.
closes #928

Lift restriction on projection, allow passing conn

---

cellrank/pl/_heatmap.py

'Iterable' has moved from 'collections' to 'collections.abc' since
Python 3.9
Resolves #942
Import `Iterable` from `collections.abc` and not `collections`. `Iterable` was removed from `collections` in Python 3.10
Tested on Python 3.10 and 3.9
#942

Fix import issue with 'Iterable' from 'collections'

---

cellrank/_utils/_colors.py

Allow NaN values when determining foreground/background color.
No test added.
closes #946

Allow for nan values in `_black_or_white`

---

.pre-commit-config.yaml
cellrank/_utils/_lineage.py
cellrank/estimators/terminal_states/_term_states_estimator.py
cellrank/models/_base_model.py
cellrank/models/_sklearn_model.py

* Bumps `isort` to `5.12.0`.
Closes #993.

Fix `isort` failure in pre-commit hooks

---

cellrank/estimators/terminal_states/_term_states_estimator.py

Very minor fix to adapt the allowed options in macrostate plotting.

Fix error message about allowed plotting types

---

cellrank/pl/_gene_trend.py

Fix lineage color map in :func:`cellrank.pl.gene_trends`.
No new tests.
closes #1042

Fix gene trends colors

---

src/cellrank/models/_pygam_model.py

Expose pygam model penalties via spline_kwargs. Before it was set to `penalties=["derivative", "l2"]` in the code. Now, the user can change the default by using: `spline_kwargs={'penalties':['derivative']}`
Tested with my own data pipeline. Does not change default parameter.
closes #1126

expose pygam model penalties via spline_kwargs fixes #1126

---

pyproject.toml
src/cellrank/_utils/_colors.py
src/cellrank/_utils/_lineage.py
src/cellrank/_utils/_linear_solver.py
src/cellrank/_utils/_utils.py
src/cellrank/estimators/mixins/_fate_probabilities.py
src/cellrank/estimators/terminal_states/_gpcca.py
src/cellrank/estimators/terminal_states/_term_states_estimator.py
src/cellrank/kernels/_precomputed_kernel.py
src/cellrank/kernels/_real_time_kernel.py
src/cellrank/kernels/_utils.py
src/cellrank/kernels/utils/_random_walk.py
src/cellrank/kernels/utils/_tmat_flow.py
src/cellrank/models/_base_model.py
src/cellrank/pl/_aggregate_fate_probs.py
src/cellrank/pl/_circular_projection.py
src/cellrank/pl/_heatmap.py
src/cellrank/pl/_utils.py
tests/_helpers.py
tests/test_cflare.py
tests/test_colors.py
tests/test_gpcca.py
tests/test_kernels.py
tests/test_lineage.py
tests/test_pipeline.py
tests/test_plotting.py
tests/test_utils.py

TODOs:
closes #1128 
closes #1134

Fix pandas/PETSc issues

---

src/cellrank/models/_pygam_model.py

* Rename `"inverse-squared"` to `"inv_squared"`.
Closes #1170.

Update pyGAM link function

---

tests/test_kernels.py

Update `TestRealTimeKernel::test_explicit_shuffle` to convert Pandas Series to a list before subsetting sparse matrix.
Closes #1251.

Fix `TestRealTimeKernel::test_explicit_shuffle`

---

.github/workflows/test.yml
pyproject.toml
src/cellrank/_utils/_lineage.py

- Deprecates Python 3.9 which is EOL. To be honest, I would jump immediately to 3.11+ (spec-0) or even 3.12+ (spec-0 in 2 months)
- Fixes https://github.com/theislab/cellrank/issues/1261

fix np str repr
